/**
 * el2en.ts — Greek→English phrase dictionary for full-app runtime translation.
 *
 * Used by <Localizer> to translate the rendered DOM when locale is "en",
 * covering hardcoded Greek strings across all screens without per-file edits.
 * Keys are exact trimmed Greek strings; values are the English equivalents.
 * Entries are ordered longest-first so multi-word phrases match before words.
 */
export const EL_TO_EN: Record<string, string> = {
  'Ο χάρτης χρησιμοποιεί δείγμα δεδομένων. Η αρχιτεκτονική είναι έτοιμη για πραγματικά γεωγραφικά δεδομένα και ενσωμάτωση με υπηρεσίες χαρτών.': 'The map uses sample data. The architecture is ready for real geographic data and integration with map services.',
  'Δεν υπάρχουν πραγματικές ειδοποιήσεις ακόμη. Παρακάτω εμφανίζονται demo παραδείγματα.': 'No real notifications yet. Demo examples are shown below.',
  'Συνδέουμε παραγωγούς και εμπόρους σε όλη την Ελλάδα σε μια δίκαιη και διαφανή αγορά.': 'We connect producers and traders across Greece in a fair and transparent market.',
  'Η διαγραφή λογαριασμού είναι μη αναστρέψιμη. Όλα τα δεδομένα σου θα διαγραφούν.': 'Account deletion is irreversible. All your data will be deleted.',
  'AgroExchange — αγρότης, θεριζοαλωνιστική, μεταφορά και σιλό στο ηλιοβασίλεμα': 'AgroExchange — farmer, combine, transport and silo at sunset',
  'Σύνδεση παραγωγών, αγοραστών και μεταφορέων αγροτικών προϊόντων στην Ελλάδα.': 'Connecting producers, buyers and transporters of agricultural products in Greece.',
  'Γεια σου! Είμαι ο βοηθός του AgroExchange. Πώς μπορώ να σε βοηθήσω σήμερα;': 'Hi! I\'m the AgroExchange assistant. How can I help you today?',
  'Παραγωγοί, αγοραστές και μεταφορείς σε όλη την Ελλάδα σε μία πλατφόρμα.': 'Producers, buyers and transporters across Greece on one platform.',
  'Αγγελίες αγροτικών προϊόντων με άμεση επικοινωνία παραγωγού-αγοραστή.': 'Agricultural product listings with direct producer-buyer communication.',
  'Διαφάνεια και αξιοπιστία με σύστημα Trust Score και αξιολογήσεις.': 'Transparency and reliability with a Trust Score system and reviews.',
  'Προστασία από καιρικά φαινόμενα, ασθένειες και απώλεια παραγωγής.': 'Protection from weather events, diseases and production loss.',
  'Έγκριτοι μεταφορείς για τη μεταφορά προϊόντων σε όλη την Ελλάδα.': 'Trusted carriers for transporting products across Greece.',
  'Χωράφι σιταριού στο ηλιοβασίλεμα με θεριζοαλωνιστική και τρακτέρ': 'Wheat field at sunset with combine and tractor',
  'Η ζήτηση διαδρομής δημοσιεύτηκε! Οι μεταφορείς θα ειδοποιηθούν.': 'Route request published! Transporters will be notified.',
  'Βρες αξιολογημένη μεταφορική για την αποστολή σου με ένα κλικ.': 'Find a rated carrier for your shipment with one click.',
  'Η κράτηση υποβλήθηκε! Ο μεταφορέας θα επικοινωνήσει μαζί σας.': 'Booking submitted! The carrier will contact you.',
  'Ενημερώσου καθημερινά για τις τιμές των αγροτικών προϊόντων.': 'Stay updated daily on agricultural product prices.',
  'Βρείτε αξιόπιστες μεταφορικές εταιρείες σε όλη την Ελλάδα.': 'Find reliable transport companies across Greece.',
  'Δωρεάν εγγραφή · Χωρίς πιστωτική κάρτα · Έτοιμο σε 2 λεπτά': 'Free registration · No credit card · Ready in 2 minutes',
  'Supabase cached · Προσθέστε NEWS_API_KEY για live ειδήσεις': 'Supabase cached · Add NEWS_API_KEY for live news',
  'Δες τις πιο πρόσφατες αγγελίες ή δημιούργησε τη δική σου.': 'Browse the latest listings or create your own.',
  'Προσθέστε NEXT_PUBLIC_NEWS_API_KEY για αυτόματες ειδήσεις': 'Add NEXT_PUBLIC_NEWS_API_KEY for automatic news',
  'Συχνές ερωτήσεις και οδηγίες χρήσης για την AgroExchange.': 'FAQ and usage guides for AgroExchange.',
  'Ελέγξτε πρόγνωση 5 ημερών πριν προγραμματίσετε συγκομιδή': 'Check the 5-day forecast before scheduling harvest',
  'Ασφαλιστικές λύσεις σχεδιασμένες για τον αγροτικό τομέα': 'Insurance solutions designed for the agricultural sector',
  'Κάλυψη εμπορευμάτων κατά τη μεταφορά σε όλη την Ελλάδα.': 'Cargo coverage during transport across Greece.',
  'Προστασία αποθηκευμένων προϊόντων από ζημιές και κλοπή.': 'Protection of stored products from damage and theft.',
  'Ζητήσεις μεταφοράς από χρήστες που αναζητούν μεταφορέα': 'Transport requests from users seeking a carrier',
  'Άρθρα για παραγωγούς, αγοραστές και την αγροτική αγορά': 'Articles for producers, buyers and the agricultural market',
  'Αποφύγετε ψεκασμούς αν ο άνεμος υπερβαίνει τα 15 km/h': 'Avoid spraying if wind exceeds 15 km/h',
  'Εγγύηση πληρωμής και προστασία από αθέτηση συμφωνιών.': 'Payment guarantee and protection against breach of agreements.',
  'Το email χρησιμοποιείται ήδη από υπάρχον λογαριασμό.': 'This email is already used by an existing account.',
  'Πραγματική επίδραση στην ελληνική αγροτική οικονομία': 'Real impact on the Greek agricultural economy',
  'Demo δεδομένα — ενημερώνονται κάθε 2.5 δεκτερόλεπτα': 'Demo data — updated every 2.5 seconds',
  'Δημοσίευσε ζήτηση και οι μεταφορείς θα ειδοποιηθούν': 'Post a request and transporters will be notified',
  'Δοκίμασε διαφορετική αναζήτηση, κατηγορία ή μονάδα': 'Try a different search, category or unit',
  'Ο κωδικός πρέπει να είναι τουλάχιστον 6 χαρακτήρες': 'Password must be at least 6 characters',
  'Αγορά μεταφορών — βρες μεταφορέα ή ζήτησε διαδρομή': 'Transport marketplace — find a carrier or request a route',
  'Φρέσκες αγγελίες από παραγωγούς σε όλη την Ελλάδα': 'Fresh listings from producers across Greece',
  'Θα ειδοποιηθείς για νέες προσφορές, deals και νέα': 'You\'ll be notified about new offers, deals and news',
  'Εξειδίκευση στη μεταφορά σιτηρών και ελαιολάδου.': 'Specializing in cereals and olive oil transport.',
  'Demo δεδομένα — προσθέστε OpenWeatherMap API key': 'Demo data — add an OpenWeatherMap API key',
  'Η κατάταξη θα εμφανιστεί μόλις γίνουν συναλλαγές': 'Rankings will appear once transactions occur',
  'Η σελίδα που ψάχνεις δεν υπάρχει ή μετακινήθηκε.': 'The page you\'re looking for doesn\'t exist or was moved.',
  'Προαιρετική περιγραφή ποιότητας, συνθηκών κ.λπ.': 'Optional description of quality, conditions, etc.',
  'Το αίτημα στάλθηκε! Θα επικοινωνήσουμε σύντομα.': 'Request sent! We will contact you soon.',
  'Αγροτικά σημεία ενδιαφέροντος σε όλη την Ελλάδα': 'Agricultural points of interest across Greece',
  'Χτίσε το μέλλον της αγροτικής αγοράς μαζί μας': 'Build the future of the agricultural market with us',
  'Αναζήτηση τίτλου, κατηγορίας ή τοποθεσίας...': 'Search title, category or location...',
  'Η προσφορά εγκρίθηκε! Το deal δημιουργήθηκε.': 'Offer approved! Deal created.',
  'Δημιούργησε αγγελίες για να λάβεις προσφορές': 'Create listings to receive offers',
  'Ασφαλείς συναλλαγές και προστασία δεδομένων': 'Secure transactions and data protection',
  'Δεν υπάρχουν κριτικές ακόμη. Γίνε ο πρώτος!': 'No reviews yet. Be the first!',
  'Ανοιχτές θέσεις εργασίας στην AgroExchange.': 'Open job positions at AgroExchange.',
  'Απαντήσεις στις πιο συνηθισμένες ερωτήσεις': 'Answers to the most common questions',
  'Συνδεθείτε με αγοραστές σε όλη την Ελλάδα': 'Connect with buyers across Greece',
  'Γίνε ο πρώτος που θα δημιουργήσει αγγελία': 'Be the first to create a listing',
  'Μπορώ να ανεβάσω φωτογραφία στην αγγελία;': 'Can I upload a photo to my listing?',
  'Πραγματικά δεδομένα από όλη την πλατφόρμα': 'Real data from across the platform',
  'Ξεκίνα συζήτηση από ένα προφίλ ή αγγελία': 'Start a chat from a profile or listing',
  'Ξεκάθαρες τιμές και όλες οι πληροφορίες': 'Clear prices and all the information',
  'Η τιμή πρέπει να είναι μεγαλύτερη από 0': 'Price must be greater than 0',
  'Ευνοϊκές συνθήκες για άρδευση βαμβακιού': 'Favorable conditions for cotton irrigation',
  'Πληκτρολόγησε ΔΙΑΓΡΑΦΗ για επιβεβαίωση': 'Type DELETE to confirm',
  'Το αρχείο πρέπει να είναι κάτω από 2MB': 'File must be under 2MB',
  'Δημιούργησε την πρώτη ζήτηση μεταφοράς': 'Create the first transport request',
  'Ορατότητα Στοιχείων στο Δημόσιο Προφίλ': 'Detail Visibility on Public Profile',
  'Top rated μεταφορέας Βορείου Ελλάδας.': 'Top rated carrier in Northern Greece.',
  'Θα ειδοποιηθείς μόλις είναι διαθέσιμο': 'You\'ll be notified when available',
  'Γιατί να δουλέψεις στην AgroExchange;': 'Why work at AgroExchange?',
  'Δεν ήταν δυνατή η έναρξη συνομιλίας': 'Could not start conversation',
  'Ο κωδικός σου ενημερώθηκε επιτυχώς.': 'Your password was updated successfully.',
  'Εξειδίκευση σε φρούτα και λαχανικά.': 'Specializing in fruits and vegetables.',
  'Δεν υπάρχουν εισερχόμενες προσφορές': 'No incoming offers',
  'Θέλετε να επικοινωνήσουμε μαζί σας;': 'Want us to contact you?',
  'Στάλθηκε email επαναφοράς κωδικού!': 'Password reset email sent!',
  'Ο λογαριασμός σου θα ενεργοποιηθεί': 'Your account will be activated',
  'Συμπλήρωσε όνομα, email και μήνυμα': 'Fill in name, email and message',
  'Είμαστε εδώ για να σας βοηθήσουμε': 'We are here to help you',
  'Πίνακας τιμών αγροτικών προϊόντων': 'Agricultural product price table',
  'Δεν έχεις στείλει προσφορές ακόμη': 'You haven\'t sent any offers yet',
  'Συμπλήρωσε αφετηρία και προορισμό': 'Fill in origin and destination',
  'Η αγροτική αγορά γίνεται ψηφιακή': 'Agriculture goes digital',
  'Είμαστε εδώ για να σε βοηθήσουμε': 'We are here to help you',
  'Βρες προϊόντα από όλη την Ελλάδα': 'Find products from all over Greece',
  'Κάτι πήγε στραβά. Δοκίμασε ξανά.': 'Something went wrong. Try again.',
  'Δεν ήταν δυνατή η φόρτωση καιρού': 'Could not load weather',
  'Πώς διαγράφω τον λογαριασμό μου;': 'How do I delete my account?',
  'Δημιουργία Δωρεάν Λογαριασμού →': 'Create Free Account →',
  'Δεν υπάρχουν αξιολογήσεις ακόμη': 'No reviews yet',
  'π.χ. Σκληρό Σιτάρι ποιότητας Α': 'e.g. Premium Durum Wheat',
  'Καμία ανοιχτή ζήτηση διαδρομής': 'No open route requests',
  'Δεν υπάρχει συνδεδεμένο προφίλ': 'No linked profile',
  '(επίλεξε έναν ή περισσότερους)': '(select one or more)',
  'Οι ασφάλειες έρχονται σύντομα!': 'Insurance is coming soon!',
  'Πώς λειτουργεί το Trust Score;': 'How does the Trust Score work?',
  'Πώς χρησιμοποιούμε τα δεδομένα': 'How we use data',
  'Αναζήτηση ονόματος ή πόλης...': 'Search name or city...',
  'Δοκίμασε διαφορετική διαδρομή': 'Try a different route',
  'Επίλεξε τουλάχιστον έναν ρόλο': 'Select at least one role',
  'Πώς επαναφέρω τον κωδικό μου;': 'How do I reset my password?',
  'Καλωσόρισες στο AgroExchange': 'Welcome to AgroExchange',
  'Προαιρετικές λεπτομέρειες...': 'Optional details...',
  'Ο λογαριασμός σου διαγράφηκε': 'Your account was deleted',
  'Ευέλικτο περιβάλλον εργασίας': 'Flexible work environment',
  'Σήμανση όλων ως αναγνωσμένα': 'Mark all as read',
  'Γράψε ένα σύντομο μήνυμα...': 'Write a short message...',
  'Περίγραψε το ερώτημά σου...': 'Describe your question...',
  'Ο τίτλος είναι υποχρεωτικός': 'Title is required',
  'Δεν υπάρχουν δεδομένα ακόμη': 'No data yet',
  'Δεν υπάρχουν αγγελίες ακόμη': 'No listings yet',
  'Άνοιγμα βοηθού AgroExchange': 'Open AgroExchange assistant',
  'Πώς λειτουργεί η πλατφόρμα;': 'How does the platform work?',
  'Το όνομα είναι υποχρεωτικό': 'Name is required',
  'Δείτε αναλυτικά τις τιμές': 'View detailed prices',
  'π.χ. Γιώργος Παπαδόπουλος': 'e.g. John Smith',
  'Οι κωδικοί δεν ταιριάζουν': 'Passwords do not match',
  'Δεν υπάρχουν ειδοποιήσεις': 'No notifications',
  'Πόλεις σε όλη την Ελλάδα': 'Cities across Greece',
  'Επιβεβαίωση Νέου Κωδικού': 'Confirm New Password',
  'Τουλάχιστον 6 χαρακτήρες': 'At least 6 characters',
  'Η αγγελία δημιουργήθηκε!': 'Listing created!',
  'Απαιτείται ονοματεπώνυμο': 'Full name is required',
  'Πώς ήταν η εμπειρία σου;': 'How was your experience?',
  'Αυτό είναι το προφίλ σου': 'This is your profile',
  'Επαληθευμένος Μεταφορέας': 'Verified Carrier',
  'Επαληθευμένη Ασφαλιστική': 'Verified Insurer',
  'χωρίς επιβεβαίωση email.': 'without email confirmation.',
  'Εκδήλωση Ενδιαφέροντος →': 'Express Interest →',
  'Δείτε όλες τις αγγελίες': 'View all listings',
  'Προβολή δημόσιου προφίλ': 'View public profile',
  'Δες όλες τις αγγελίες →': 'View all listings →',
  'Δεν βρέθηκαν μεταφορείς': 'No transporters found',
  'Γράψε το ερώτημά σου...': 'Type your question...',
  'Η προσφορά απορρίφθηκε.': 'Offer rejected.',
  'Η φωτογραφία αφαιρέθηκε': 'Photo removed',
  'Επαληθευμένη Επιχείρηση': 'Verified Business',
  '← Επιστροφή στην αρχική': '← Back to home',
  'Η εγγραφή είναι δωρεάν;': 'Is registration free?',
  'Ανταγωνιστικές αποδοχές': 'Competitive salary',
  'Δημιουργία Λογαριασμού': 'Create Account',
  'Είσοδος στην Πλατφόρμα': 'Sign in to the Platform',
  'Σήμανση ως αναγνωσμένο': 'Mark as read',
  'Κανονίζεις τη μεταφορά': 'Arrange transport',
  'Έτοιμος να ξεκινήσεις;': 'Ready to get started?',
  'Λίγα λόγια για σένα...': 'A few words about you...',
  'Προτιμώμενη ημερομηνία': 'Preferred date',
  'Τηλέφωνο (προαιρετικό)': 'Phone (optional)',
  'Η αγγελία ενημερώθηκε!': 'Listing updated!',
  'Το προφίλ ενημερώθηκε!': 'Profile updated!',
  'Ο κωδικός ενημερώθηκε!': 'Password updated!',
  'Πώς δημιουργώ αγγελία;': 'How do I create a listing?',
  'Τι δεδομένα συλλέγουμε': 'What data we collect',
  'Επεξεργασία Στοιχείων': 'Edit Details',
  'Αληθινές τιμές αγοράς': 'Real market prices',
  'Συμφωνείς με αγοραστή': 'Agree with buyer',
  'Εγγεγραμμένοι Χρήστες': 'Registered Users',
  'Καθαρισμός αναζήτησης': 'Clear search',
  'Δεν βρέθηκαν αγγελίες': 'No listings found',
  'Η κριτική υποβλήθηκε!': 'Review submitted!',
  'Η φωτογραφία ανέβηκε!': 'Photo uploaded!',
  'Λάθος email ή κωδικός': 'Wrong email or password',
  'Σύνδεση με Live Καιρό': 'Connect to Live Weather',
  'Δεν υπάρχουν δεδομένα': 'No data',
  'Επίλεξε μια συνομιλία': 'Select a conversation',
  'Ο χρήστης δεν βρέθηκε': 'User not found',
  'Επαληθευμένος Χρήστης': 'Verified User',
  'Έχεις ήδη λογαριασμό;': 'Already have an account?',
  'Δεν έχεις λογαριασμό;': 'Don\'t have an account?',
  '(ένας ή περισσότεροι)': '(one or more)',
  'Έρχονται οι Ασφάλειες': 'Insurance is coming',
  'Ασφάλιση Καλλιεργειών': 'Crop Insurance',
  'Πώς βρίσκω μεταφορέα;': 'How do I find a carrier?',
  'Πώς βρίσκω αγοραστές;': 'How do I find buyers?',
  'Επικοινώνησε μαζί μας': 'Contact us',
  'Στοιχεία Επικοινωνίας': 'Contact Details',
  'Δικαιώματά σου (GDPR)': 'Your rights (GDPR)',
  'Κοινοποίηση δεδομένων': 'Data sharing',
  'Επεξεργασία Αγγελίας': 'Edit Listing',
  'Διαγραφή Λογαριασμού': 'Delete Account',
  'Αφαίρεση φωτογραφίας': 'Remove photo',
  'Νέα Ζήτηση Διαδρομής': 'New Route Request',
  'Μήνυμα (προαιρετικό)': 'Message (optional)',
  'Η αγγελία διαγράφηκε': 'Listing deleted',
  'Γιώργος Παπαδόπουλος': 'George Papadopoulos',
  'Ασφάλιση Αποθήκευσης': 'Storage Insurance',
  'Βοήθεια με μεταφορές': 'Help with transport',
  'Πώς στέλνω προσφορά;': 'How do I send an offer?',
  'Η σελίδα δεν βρέθηκε': 'Page not found',
  'Δεν βρήκες απάντηση;': 'Didn\'t find an answer?',
  'Δημιουργία Αγγελίας': 'Create Listing',
  'Τιμές Αγοράς Σήμερα': 'Today\'s Market Prices',
  'Ασφαλείς συναλλαγές': 'Secure transactions',
  'Ασφαλείς Συναλλαγές': 'Secure Transactions',
  'Δημιουργείς αγγελία': 'Create a listing',
  'Λαμβάνεις προσφορές': 'Receive offers',
  'LIVE · Τιμές Αγοράς': 'LIVE · Market Prices',
  'Δεν βρέθηκαν σημεία': 'No points found',
  'Επιβεβαίωση Κωδικού': 'Confirm Password',
  'Ξέχασες τον κωδικό;': 'Forgot your password?',
  'Εταιρείες Μεταφορών': 'Transport Companies',
  'Καιρός & Προγνώσεις': 'Weather & Forecasts',
  'Αγροτικές Συστάσεις': 'Agricultural Recommendations',
  'Διάβασε περισσότερα': 'Read more',
  'Επιλέξτε βαθμολογία': 'Select a rating',
  'Εμφάνιση τοποθεσίας': 'Show location',
  'Ασφάλιση Συναλλαγών': 'Transaction Insurance',
  'Βοηθός AgroExchange': 'AgroExchange Assistant',
  'Βοήθεια με αγγελίες': 'Help with listings',
  'AgroExchange αρχική': 'AgroExchange home',
  'Πήγαινε στην Αρχική': 'Go to Home',
  'Ποιους εξυπηρετούμε': 'Who we serve',
  'Παραγωγοί & αγρότες': 'Producers & farmers',
  'Αγοραστές & έμποροι': 'Buyers & traders',
  'Δείτε λεπτομέρειες': 'View details',
  'Αποστολή Προσφοράς': 'Send Offer',
  'Αποστολή Μηνύματος': 'Send Message',
  'Αποστολή Αιτήματος': 'Send Request',
  'Αποθήκευση Κωδικού': 'Save Password',
  'Αλλαγή φωτογραφίας': 'Change photo',
  'Δημοσίευση Ζήτησης': 'Publish Request',
  'Πρόσφατες Αγγελίες': 'Recent Listings',
  'Γιατί AgroExchange': 'Why AgroExchange',
  'Πανελλαδική κάλυψη': 'Nationwide coverage',
  'Αναζήτηση πόλης...': 'Search city...',
  'Δεν βρέθηκαν άρθρα': 'No articles found',
  'Η προσφορά εστάλη!': 'Offer sent!',
  'Απαιτείται κωδικός': 'Password is required',
  'Σφάλμα ανεβάσματος': 'Upload error',
  'Ζητήσεις Διαδρομής': 'Route Requests',
  'Ξεκίνα τη συζήτηση': 'Start the conversation',
  'Εμφάνιση τηλεφώνου': 'Show phone',
  'Ασφάλιση Μεταφορών': 'Transport Insurance',
  'Dashboard πλοήγηση': 'Dashboard navigation',
  'Πολιτική Απορρήτου': 'Privacy Policy',
  '← Πίσω στην είσοδο': '← Back to login',
  'Email Επιχειρήσεων': 'Business Email',
  'Δε–Πα, 09:00–17:00': 'Mon–Fri, 09:00–17:00',
  'αγροτικά προϊόντα': 'agricultural products',
  'Οριστική Διαγραφή': 'Permanent Deletion',
  'Επαναφορά Κωδικού': 'Reset Password',
  'Όλες αναγνωσμένες': 'All read',
  'π.χ. giorgos_farm': 'e.g. john_farm',
  'Πόλη αποστολής...': 'Origin city...',
  'Πόλη παραλαβής...': 'Destination city...',
  'Ο κωδικός άλλαξε!': 'Password changed!',
  'Φορτηγό Iveco 15t': 'Iveco 15t Truck',
  'Φορτηγό Volvo 25t': 'Volvo 25t Truck',
  'Νίκος Σταθόπουλος': 'Nikos Stathopoulos',
  'Ανδρέας Δημητρίου': 'Andreas Dimitriou',
  'Νέα & Ενημερώσεις': 'News & Updates',
  'Email Υποστήριξης': 'Support Email',
  'Πλήρης Απασχόληση': 'Full Time',
  'Υποβολή Κριτικής': 'Submit Review',
  'Η αγροτική αγορά': 'The agricultural market',
  'σε μία πλατφόρμα': 'in one platform',
  'Μεταφορές εύκολα': 'Transport made easy',
  'Ενεργές Αγγελίες': 'Active Listings',
  'Δεν βρέθηκε πόλη': 'No city found',
  'Συνδεθείτε πρώτα': 'Please log in first',
  'Απαιτείται email': 'Email is required',
  'Ζήτηση Διαδρομής': 'Route Request',
  'Κατάταξη Χρηστών': 'User Rankings',
  'Κριτικές Χρηστών': 'User Reviews',
  'για επιβεβαίωση:': 'for confirmation:',
  'Ώρες Υποστήριξης': 'Support Hours',
  'Δείτε μεταφορές': 'View transport',
  'με τον αγοραστή': 'with the buyer',
  'Μονάδα μέτρησης': 'Unit of measurement',
  'Γράψε μήνυμα...': 'Write a message...',
  'Μη έγκυρο email': 'Invalid email',
  'Σφάλμα εγγραφής': 'Registration error',
  'Κέντρα Διανομής': 'Distribution Centers',
  'Φορτηγό MAN 18t': 'MAN 18t Truck',
  'Μέση βαθμολογία': 'Average rating',
  'Ολοκλήρωση Deal': 'Complete Deal',
  'Καμία συνομιλία': 'No conversations',
  'Επικίνδυνη Ζώνη': 'Danger Zone',
  'Επιλογή γλώσσας': 'Select language',
  'Κέντρο Βοήθειας': 'Help Center',
  'Ανοιχτές Θέσεις': 'Open Positions',
  'Όλες οι πόλεις': 'All cities',
  'Δείτε Αγγελίες': 'View Listings',
  'Αποστολή Email': 'Send Email',
  'Αλλαγή Κωδικού': 'Change Password',
  'Πίσω στη λίστα': 'Back to list',
  'Πώς λειτουργεί': 'How it works',
  'Το οικοσύστημα': 'The ecosystem',
  'Σύνδεση παντού': 'Connect everywhere',
  'Αποσυνδεθήκατε': 'Logged out',
  'Συνολικά Deals': 'Total Deals',
  'Εμφάνιση email': 'Show email',
  'Ερώτηση χρήσης': 'Usage question',
  'Κύρια πλοήγηση': 'Main navigation',
  'Κανόνες Χρήσης': 'Usage Rules',
  'Αθήνα / Remote': 'Athens / Remote',
  'Η αποστολή μας': 'Our mission',
  'Τι προσφέρουμε': 'What we offer',
  'Γράψε Κριτική': 'Write Review',
  'Δοκίμασε ξανά': 'Try again',
  'Βρες Μεταφορά': 'Find Transport',
  'Στο Dashboard': 'Go to Dashboard',
  'Live ειδήσεις': 'Live news',
  'Πίνακας Τιμών': 'Price Table',
  'Το μήνυμά σου': 'Your message',
  'Ονοματεπώνυμο': 'Full name',
  'Πληκτρολόγησε': 'Type',
  'Συνεταιρισμοί': 'Cooperatives',
  '✓ Deal ενεργό': '✓ Deal active',
  'Νέα συνομιλία': 'New conversation',
  'Προφίλ Χρήστη': 'User Profile',
  'Αθήνα, Ελλάδα': 'Athens, Greece',
  'Αρχική Σελίδα': 'Home Page',
  'Ειδοποιήσεις': 'Notifications',
  'Ολοκληρώθηκε': 'Completed',
  'Δες Αγγελίες': 'View Listings',
  'Τιμές Αγοράς': 'Market Prices',
  'Δημιουργείτε': 'Create',
  'Το όνομά σου': 'Your name',
  'Νέος Κωδικός': 'New Password',
  'Νέος κωδικός': 'New password',
  'Καλώς ήρθες!': 'Welcome!',
  'Μέσος χρόνος': 'Average time',
  'Νέα Προσφορά': 'New Offer',
  'Εισερχόμενες': 'Incoming',
  'Επίλεξε ρόλο': 'Select role',
  'Επικοινωνία': 'Contact',
  'Απορρίφθηκε': 'Rejected',
  'Επιτυχημένα': 'Successful',
  'Ασφαλιστική': 'Insurer',
  'Επεξεργασία': 'Edit',
  'Αντιπρόταση': 'Counter-offer',
  'Περισσότερα': 'More',
  'Αποστολή...': 'Sending...',
  'Νέα Αγγελία': 'New Listing',
  'τη μεταφορά': 'transport',
  'π.χ. Λάρισα': 'e.g. Larissa',
  'π.χ. Σιτάρι': 'e.g. Wheat',
  'Προς (πόλη)': 'To (city)',
  'Επιδοτήσεις': 'Subsidies',
  'Θεσσαλονίκη': 'Thessaloniki',
  'Πορτοκάλια': 'Oranges',
  'πορτοκάλια': 'oranges',
  'Αποσύνδεση': 'Log out',
  'Βαθμολογία': 'Rating',
  'Αξιολόγηση': 'Review',
  'Στατιστικά': 'Statistics',
  'Διαδικασία': 'Process',
  'Συνεργασία': 'Partnership',
  'Μεταφορέας': 'Transporter',
  'Μεταφορείς': 'Carriers',
  'Αποθήκευση': 'Save',
  'Δημοσίευση': 'Publish',
  'Καθαρισμός': 'Clear',
  'Live Τιμές': 'Live Prices',
  'Υποστήριξη': 'Support',
  'Αξιοπιστία': 'Reliability',
  'Συμφωνείτε': 'Agree',
  'Κανονίζετε': 'Arrange',
  'Χαμηλό 24ω': '24h Low',
  'εκτιμώμενο': 'estimated',
  'π.χ. Αθήνα': 'e.g. Athens',
  'Από (πόλη)': 'From (city)',
  'Σημειώσεις': 'Notes',
  'Τεχνολογία': 'Technology',
  'Καλαμπόκι': 'Corn',
  'Ελαιόλαδο': 'Olive Oil',
  'καλαμπόκι': 'corn',
  'ελαιόλαδο': 'olive oil',
  'πορτοκάλι': 'orange',
  'παραγωγοί': 'producers',
  'προσφορές': 'offers',
  'Μεταφορές': 'Transport',
  'Ασφάλειες': 'Insurance',
  'Προσφορές': 'Offers',
  'Κατηγορία': 'Category',
  'Τοποθεσία': 'Location',
  'Περιγραφή': 'Description',
  'Πλατφόρμα': 'Platform',
  'Δημοφιλές': 'Popular',
  'Εγκρίθηκε': 'Approved',
  'Παραγωγός': 'Producer',
  'Αγοραστής': 'Buyer',
  'Λιγότερες': 'Less',
  'Προσθέστε': 'Add',
  'Διαφάνεια': 'Transparency',
  'Λαμβάνετε': 'Receive',
  'Υψηλό 24ω': '24h High',
  'Επιτυχία!': 'Success!',
  'Νομοθεσία': 'Legislation',
  'Ευρωπαϊκά': 'European',
  'Ηλίανθος': 'Sunflower',
  'ηλίανθος': 'sunflower',
  'κοτόπουλ': 'chicken',
  'Αγγελίες': 'Listings',
  'Μηνύματα': 'Messages',
  'Κατάταξη': 'Rankings',
  'Ποσότητα': 'Quantity',
  'Αξία (€)': 'Value (€)',
  'Μεταβολή': 'Change',
  'Πωλήσεις': 'Sales',
  'Εταιρεία': 'Company',
  'Απόρρητο': 'Privacy',
  'Τρέχουσα': 'Current',
  'Εκκρεμής': 'Pending',
  'Αποστολή': 'Send',
  'Κλείσιμο': 'Close',
  'Διαγραφή': 'Delete',
  'Πρόσθεσε': 'Add',
  'Κριτικές': 'Reviews',
  'αλλάζει.': 'is changing.',
  'Ασφάλεια': 'Security',
  'Τηλέφωνο': 'Phone',
  'ΔΙΑΓΡΑΦΗ': 'DELETE',
  'Αποθήκες': 'Warehouses',
  'Υπόμνημα': 'Legend',
  'Ανώνυμος': 'Anonymous',
  'Ελληνικά': 'Greek',
  'Για εμάς': 'About Us',
  '← Αρχική': '← Home',
  'Βαμβάκι': 'Cotton',
  'Κριθάρι': 'Barley',
  'βαμβάκι': 'cotton',
  'κριθάρι': 'barley',
  'κρεμμύδ': 'onion',
  'ροδάκιν': 'peach',
  'αγρότες': 'farmers',
  'αγγελία': 'listing',
  'Σύνδεση': 'Log in',
  'Εγγραφή': 'Sign up',
  'Είσοδος': 'Log in',
  'Σύστημα': 'System',
  'Χρήστης': 'User',
  'Σύμβαση': 'Contract',
  'Καριέρα': 'Careers',
  'Βοήθεια': 'Help',
  'Κανόνες': 'Rules',
  'Σύντομα': 'Soon',
  'Επείγον': 'Urgent',
  'Ακύρωση': 'Cancel',
  'Άνοιγμα': 'Open',
  'Αποδοχή': 'Accept',
  'Κράτηση': 'Book',
  'Μονάδα:': 'Unit:',
  'π.χ. 20': 'e.g. 20',
  'Κωδικός': 'Password',
  'Σιτάρι': 'Wheat',
  'Τομάτα': 'Tomato',
  'σιτάρι': 'wheat',
  'τομάτα': 'tomato',
  'ηλίανθ': 'sunflower',
  'αγελάδ': 'cow',
  'κατσίκ': 'goat',
  'μοσχάρ': 'veal',
  'πρόβατ': 'sheep',
  'σταφύλ': 'grape',
  'Αρχική': 'Home',
  'Χάρτης': 'Map',
  'Καιρός': 'Weather',
  'Προφίλ': 'Profile',
  'Τίτλος': 'Title',
  'Σχόλιο': 'Comment',
  'Προϊόν': 'Product',
  'Οδηγός': 'Guide',
  'Αγορές': 'Purchases',
  'Αλλαγή': 'Change',
  'Άρνηση': 'Decline',
  'Μήνυμα': 'Message',
  'Σύνολο': 'Total',
  'Ελλάδα': 'Greece',
  'Λάρισα': 'Larissa',
  'σιτηρ': 'cereals',
  'τομάτ': 'tomato',
  'αμπέλ': 'vineyard',
  'αχλάδ': 'pear',
  'κεράσ': 'cherry',
  'λεμόν': 'lemon',
  'πατάτ': 'potato',
  'αγορά': 'market',
  'Αγορά': 'Market',
  'Όνομα': 'Name',
  'Ρόλος': 'Role',
  'Ρόλοι': 'Roles',
  'Μέλος': 'Member',
  'Άκυρο': 'Cancel',
  'Μύλοι': 'Mills',
  'Αθήνα': 'Athens',
  'Πάτρα': 'Patras',
  'Ξάνθη': 'Xanthi',
  'Ρύζι': 'Rice',
  'Άλλο': 'Other',
  'ρύζι': 'rice',
  'αρνί': 'lamb',
  'ελιά': 'olive',
  'χοίρ': 'pig',
  'Πόλη': 'City',
  'Όλες': 'All',
  'Τιμή': 'Price',
  'Αξία': 'Value',
  'Προς': 'To',
  'Θέμα': 'Subject',
  'Πηγή': 'Source',
  'Όροι': 'Terms',
  'Πίσω': 'Back',
  'Σιλό': 'Silos',
  'βόδ': 'ox',
  'γίδ': 'goat',
  'μήλ': 'apple',
  'Νέα': 'New',
  'Όλα': 'All',
  'Από': 'From',
  'Νέο': 'New',
  'στο': 'to',
  '48ω': '48h',
  '24ω': '24h',
  '/τ': '/t',
  'ΜΤ': 'MT',
}
